Adds a plugin family package to be shared across our plugins
wp-media/plugin-family pull request #1
Opened 2024-10-15 09:12 UTC by jeawhanlee

# Description
A package to organise and display WP Media plugin family across other members.

Fixes https://github.com/wp-media/imagify-plugin/issues/908

*Explain how this code impacts users.*
Displays the WP Media plugin family across other member plugins.

## Type of change

- [x] Release

## Detailed scenario

No Issue

## Technical description

### Documentation

A composer package that gathers all the member plugins data and sorts them based on activated status ordered by `categorized` or `uncategorized` and then adds a controller handler to perform installation & activation actions.

### New dependencies

N/A

### Risks

N/A

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

# Additional Checks
- [x] In the case of complex code, I wrote comments to explain it.
- [x] When possible, I prepared ways to observe the implemented system (logs, data, etc.).
- [x] I added error handling logic when using functions that could throw errors (HTTP/API request, filesystem, etc.)

2024-10-15 19:00 UTC, jeawhanlee commented
The README is still WIP.

2024-10-16 09:01 UTC, jeawhanlee commented
> The README is still WIP.

Done ✅

2024-10-16 20:09 UTC, Tabrisrp requested changes
Could we update the repository name from `wp-media-plugin-family` to `plugin-family`? The namespace is already there.

We should also add PHPStan to the CI

2024-10-16 20:09 UTC, remyperona commented on src/Model/PluginFamily.php
> +namespace WPMediaPluginFamily\Model;
```suggestion
namespace WPMedia\PluginFamily\Model;
```

2024-10-16 20:09 UTC, remyperona commented on src/Model/PluginFamily.php
> +defined( 'ABSPATH' ) || exit;
```suggestion
```
Not necessary for a class

2024-10-16 20:09 UTC, remyperona commented on src/Controller/PluginFamilyInterface.php
> +defined( 'ABSPATH' ) || exit;
```suggestion
```

2024-10-16 20:09 UTC, remyperona commented on src/Controller/PluginFamilyInterface.php
> +namespace WPMediaPluginFamily\Controller;
```suggestion
namespace WPMedia\PluginFamily\Controller;
```

2024-10-16 20:09 UTC, remyperona commented on src/Controller/PluginFamily.php
> +defined( 'ABSPATH' ) || exit;
```suggestion
```

2024-10-16 20:09 UTC, remyperona commented on src/Controller/PluginFamily.php
> +namespace WPMediaPluginFamily\Controller;
```suggestion
namespace WPMedia\PluginFamily\Controller;
```

2024-10-16 20:09 UTC, Tabrisrp commented on composer.json
> +            "WPMediaPluginFamily\\": "src/",
```suggestion
            "WPMedia\PluginFamily\\": "src/",
```

2024-10-16 20:09 UTC, Tabrisrp commented on composer.json
> +            "WPMediaPluginFamily\\Tests\\": "tests/"
This should be in `autoload-dev`

2024-10-17 19:00 UTC, Tabrisrp requested changes

2024-10-17 19:00 UTC, Tabrisrp commented on tests/Unit/src/Model/PluginFamily/filterPluginsByActivation.php
> +        $this->plugin_family->method('get_current_url')->willReturn( 'http%3A%2F%2Fexample.org%2Fwp-admin' );
You can set the global variables in the test as needed instead of mocking the method

2024-10-17 19:00 UTC, Tabrisrp commented on tests/Unit/src/Model/PluginFamily/filterPluginsByActivation.php
> +        Functions\when( 'admin_url' )->justReturn( 'http://example.org/wp-admin/admin-post.php' );
```suggestion
        Functions\when( 'admin_url' )->alias(
			function ( $path ) {
				return "http://example.org/wp-admin/{$path}";
			}
		);
```

2024-10-17 19:00 UTC, Tabrisrp commented on src/Model/PluginFamily.php
> +		$plugins = require_once 'wp_media_plugins.php';
I'm not sure I see the value there compared to a get method in this class that would return the array

2024-10-17 19:00 UTC, Tabrisrp commented on phpstan.neon.dist
> +	level: 5
Did you try to go up to level 9?

2024-10-18 08:26 UTC, jeawhanlee commented on phpstan.neon.dist
> +	level: 5
Yes, I tried 9, too many complains,  I even tried 10 😂 the current version doesn't support it though.
I didn't want to slow down the developments of other depending task so maybe we release this first or WDYT?

2024-10-18 08:36 UTC, jeawhanlee commented on src/Model/PluginFamily.php
> +		$plugins = require_once 'wp_media_plugins.php';
Personally, I don't like having large arrays in classes and if more plugins join, it's going to get bigger, so this just a crude SOC implementation, so we can update data directly without going into the class.

2024-10-18 13:41 UTC, Tabrisrp commented on src/Model/PluginFamily.php
> +		$plugins = require_once 'wp_media_plugins.php';
Sounds good

2024-10-18 13:42 UTC, Tabrisrp commented on phpstan.neon.dist
> +	level: 5
We can do later

2024-10-18 13:43 UTC, Tabrisrp approved these changes

2024-10-21 08:56 UTC, merged